---
title: "WR demographic histories"
author: "Fátima S. Barreiro"
date: "April 19, 2020"
output: html_document
---

 data gathered from literature
 1. Emslie and Brooks 1999 (IUCN report on African rhinos)
 2. Rookmaaker 2000, on the alleged pop decline in SWR
 3. IUCN Red List report of 2012



```{r}
library(ggplot2)
library(reshape2)
```

```{r}
history = read.csv("WR_demographic_histories.csv", header=TRUE)

# re-shape data frame to arrange all values in one column
test <- reshape2::melt(history, id.var='year')
test2 <- na.omit(test)
```

```{r}
H = ggplot(test2, aes(x=year, y=value, color=variable)) +
  scale_color_manual(values=c('darkorange', 'steelblue4')) +
  scale_x_continuous(limits=c(1840, 2014), breaks = seq(1840, 2010, 20), expand = c(0, 0)) +
  ylab("Number of individuals") +
  
   # add the bottlenecks
  annotate("rect", xmin = 1890, xmax = 1900, ymin = 0, ymax = 20000, alpha = .3, fill='steelblue4') +
  annotate("rect", xmin = 1960, xmax = 1970, ymin = 0, ymax = 20000, alpha = .3, fill='darkorange')

```

```{r}
H = H + 
  # draw the pop trajectories
  geom_point(alpha=.8, size=1) + geom_line(size=.8) +
  
  # format axes and legend
  theme(axis.text.x = element_text(size=9, angle=45, hjust=1, face="bold"), 
        axis.line.x = element_line(color="gray20", size = .7), axis.title.x=element_blank(),
        axis.text.y = element_text(size=8, hjust=1, face="bold"), axis.title.y=element_text(size=9),
        axis.ticks= element_line(color="gray20"),
        legend.title = element_blank(), legend.text = element_text(size = 9), 
        legend.background = element_rect(fill="white", size=0.2, linetype = 0),
        legend.key.size = unit(.7, "cm"), legend.key=element_blank(),
        legend.position = "top" , legend.margin=margin(0,-10,-10,-10), legend.box.margin=margin(0,-10,-10,-10),
        panel.background = element_rect(fill='white'), 
        panel.grid.major.y = element_line(colour="gray40", size=.6, linetype=3)) +
  
  # annotate the sampling points
  annotate("rect", xmin = 1842, xmax = 1869, ymin = 15500, ymax = 15800, alpha =1, fill='steelblue4') +
  annotate("rect", xmin = 1905, xmax = 1914, ymin = 10500, ymax = 10800, alpha =1, fill='darkorange') +
  annotate("rect", xmin = 1954, xmax = 1974, ymin = 10500, ymax = 10800, alpha =1, fill='darkorange') +
  annotate("rect", xmin = 1958, xmax = 2012, ymin = 15500, ymax = 15800, alpha =1, fill='steelblue4')

H
```

```{r}
pdf('WR_v4_Fig1B_v1.pdf', height=4, width=4.5, useDingbats = F)
H
dev.off()
```

